spring:
  application:
    name: laoj-user-service
  # dev environment
  profiles:
    active: dev
  # swagger3 support
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session
  session:
    store-type: redis
    # 30 day
    timeout: 2592000
  # mysql connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lavson
    username: root
    password: qop909
  # Redis connection
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # file upload limit
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/user
    # cookie 30 day
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # logic delete field name
      logic-delete-value: 1 # deleted: 1
      logic-not-delete-value: 0 # undeleted: 0
knife4j:
  enable: true