# production environment
spring:
  # mysql connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lavson
    username: root
    password: qop909
  # Redis connection
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # file upload limit
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: guest
    username: guest
