spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: laoj-user-service
          uri: lb://laoj-user-service
          predicates:
            - Path=/api/user/**
        - id: laoj-question-service
          uri: lb://laoj-question-service
          predicates:
            - Path=/api/question/**
        - id: laoj-judge-service
          uri: lb://laoj-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: laoj-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ? ????????gateway????
    enabled: true
    # ? ??????????????discover???????
    strategy: discover
    discover:
      # ? ????????discover??
      enabled: true
      # ? ??????????????Swagger2?????
      version: swagger2